### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by jmwerner** [jmwerner/__WonderBot__#15]
Example, a 503 response

```
prawcore.exceptions.ServerError: received 503 HTTP response
Job "main (trigger: interval[0:02:00], next run at: 2017-07-16 14:08:51 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/jmwerner1123/GitHub/__WonderBot__/wonderbot.py", line 208, in main
    reddit_bot.start_comment_batch()
  File "/home/jmwerner1123/GitHub/__WonderBot__/wonderbot.py", line 155, in start_comment_batch
    for post in self.get_new_comments():
  File "/home/jmwerner1123/.local/lib/python3.5/site-packages/praw/models/listing/generator.py", line 52, in __next__
    self._next_batch()
  File "/home/jmwerner1123/.local/lib/python3.5/site-packages/praw/models/listing/generator.py", line 62, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/home/jmwerner1123/.local/lib/python3.5/site-packages/praw/reddit.py", line 320, in get
    data = self.request('GET', path, params=params)
  File "/home/jmwerner1123/.local/lib/python3.5/site-packages/praw/reddit.py", line 404, in request
    params=params)
  File "/home/jmwerner1123/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 148, in request
    params=params, url=url)
  File "/home/jmwerner1123/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 96, in _request_with_retries
    method=method, params=params, url=url, retries=retries - 1)
  File "/home/jmwerner1123/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 96, in _request_with_retries
    method=method, params=params, url=url, retries=retries - 1)
  File "/home/jmwerner1123/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 98, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.ServerError: received 503 HTTP response
Job "main (trigger: interval[0:02:00], next run at: 2017-07-16 14:12:51 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/jmwerner1123/GitHub/__WonderBot__/wonderbot.py", line 210, in main
    reddit_bot.start_submission_batch()
  File "/home/jmwerner1123/GitHub/__WonderBot__/wonderbot.py", line 160, in start_submission_batch
    for submission in self.get_new_posts():
  File "/home/jmwerner1123/.local/lib/python3.5/site-packages/praw/models/listing/generator.py", line 52, in __next__
    self._next_batch()
  File "/home/jmwerner1123/.local/lib/python3.5/site-packages/praw/models/listing/generator.py", line 62, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/home/jmwerner1123/.local/lib/python3.5/site-packages/praw/reddit.py", line 320, in get
    data = self.request('GET', path, params=params)
  File "/home/jmwerner1123/.local/lib/python3.5/site-packages/praw/reddit.py", line 404, in request
    params=params)
  File "/home/jmwerner1123/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 148, in request
    params=params, url=url)
  File "/home/jmwerner1123/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 96, in _request_with_retries
    method=method, params=params, url=url, retries=retries - 1)
  File "/home/jmwerner1123/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 96, in _request_with_retries
    method=method, params=params, url=url, retries=retries - 1)
  File "/home/jmwerner1123/.local/lib/python3.5/site-packages/prawcore/sessions.py", line 98, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.ServerError: received 503 HTTP response
```

**Comment by jmwerner** [comment]
Banned. Tabling for next bot.
